//
// AccountSealProviders.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/**  */
public final class AccountSealProviders: Content {
    /** A list of electronic seals to apply to documents. */
    public var seals: [SealIdentifier]?

    public init(seals: [SealIdentifier]? = nil) {
        self.seals = seals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(seals, forKey: .seals)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        seals = try container.decodeIfPresent([SealIdentifier].self, forKey: .seals)
    }
}

extension AccountSealProviders: Hashable {
    public static func == (lhs: AccountSealProviders, rhs: AccountSealProviders) -> Bool {
        lhs.seals == rhs.seals
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(seals?.hashValue)
    }
}
