//
// AppStoreReceipt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** Contains information about an APP store receipt. */
public final class AppStoreReceipt: Content {
    /** The Product ID from the AppStore. */
    public var productId: String?
    /** Reserved: TBD */
    public var receiptData: String?

    public init(productId: String? = nil, receiptData: String? = nil) {
        self.productId = productId
        self.receiptData = receiptData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId
        case receiptData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(receiptData, forKey: .receiptData)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        productId = try container.decodeIfPresent(String.self, forKey: .productId)
        receiptData = try container.decodeIfPresent(String.self, forKey: .receiptData)
    }
}

extension AppStoreReceipt: Hashable {
    public static func == (lhs: AppStoreReceipt, rhs: AppStoreReceipt) -> Bool {
        lhs.productId == rhs.productId &&
            lhs.receiptData == rhs.receiptData
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(productId?.hashValue)
        hasher.combine(receiptData?.hashValue)
    }
}
