//
// BillingPaymentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** Defines an billing payment response object. */
public final class BillingPaymentResponse: Content {
    /** Reserved: TBD */
    public var billingPayments: [BillingPayment]?

    public init(billingPayments: [BillingPayment]? = nil) {
        self.billingPayments = billingPayments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case billingPayments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(billingPayments, forKey: .billingPayments)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        billingPayments = try container.decodeIfPresent([BillingPayment].self, forKey: .billingPayments)
    }
}

extension BillingPaymentResponse: Hashable {
    public static func == (lhs: BillingPaymentResponse, rhs: BillingPaymentResponse) -> Bool {
        lhs.billingPayments == rhs.billingPayments
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(billingPayments?.hashValue)
    }
}
