//
// PowerFormsFormDataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/**  */
public final class PowerFormsFormDataResponse: Content {
    /** An array containing PowerForm data. */
    public var envelopes: [PowerFormFormDataEnvelope]?

    public init(envelopes: [PowerFormFormDataEnvelope]? = nil) {
        self.envelopes = envelopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case envelopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(envelopes, forKey: .envelopes)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        envelopes = try container.decodeIfPresent([PowerFormFormDataEnvelope].self, forKey: .envelopes)
    }
}

extension PowerFormsFormDataResponse: Hashable {
    public static func == (lhs: PowerFormsFormDataResponse, rhs: PowerFormsFormDataResponse) -> Bool {
        lhs.envelopes == rhs.envelopes
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(envelopes?.hashValue)
    }
}
