//
// SigningGroupInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/**  */
public final class SigningGroupInformation: Content {
    /** A collection group objects containing information about the groups. */
    public var groups: [SigningGroup]?

    public init(groups: [SigningGroup]? = nil) {
        self.groups = groups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(groups, forKey: .groups)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        groups = try container.decodeIfPresent([SigningGroup].self, forKey: .groups)
    }
}

extension SigningGroupInformation: Hashable {
    public static func == (lhs: SigningGroupInformation, rhs: SigningGroupInformation) -> Bool {
        lhs.groups == rhs.groups
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(groups?.hashValue)
    }
}
