//
// UserInfoList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/**  */
public final class UserInfoList: Content {
    /** An array of `userInfo` objects containing information about the users in the group. */
    public var users: [UserInfo]?

    public init(users: [UserInfo]? = nil) {
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        try container.encodeIfPresent(users, forKey: .users)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        users = try container.decodeIfPresent([UserInfo].self, forKey: .users)
    }
}

extension UserInfoList: Hashable {
    public static func == (lhs: UserInfoList, rhs: UserInfoList) -> Bool {
        lhs.users == rhs.users
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(users?.hashValue)
    }
}
