//
// BulkRecipientsUpdateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/**  */
public final class BulkRecipientsUpdateResponse: Content, Hashable {
    public var signer: Signer?

    public init(signer: Signer? = nil) {
        self.signer = signer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signer
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(signer, forKey: .signer)
    }

    public static func == (lhs: BulkRecipientsUpdateResponse, rhs: BulkRecipientsUpdateResponse) -> Bool {
        lhs.signer == rhs.signer
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(signer?.hashValue)
    }
}
