//
// BulkSendingCopyTab.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/** A tab associated with the bulk send recipient. In a bulk send request, each recipient tab must match a recipient tab on the envelope or template that you want to send. To match up, the &#x60;tabLabel&#x60; for this tab and the &#x60;tabLabel&#x60; for the corresponding tab on the envelope or template must be the same.  For example, if the envelope has a placeholder text tab with the &#x60;tabLabel&#x60; &#x60;childName&#x60;, you must assign the same &#x60;tabLabel&#x60; &#x60;childName&#x60; to the tab here that you are populating with that information. */
public final class BulkSendingCopyTab: Content, Hashable {
    /** The initial value that you want to assign to the tab. */
    public var initialValue: String?
    /** The label associated with the recipient tab. In a bulk send request, the `tabLabel` for this tab and the `tabLabel` for the corresponding tab on the envelope or template must be the same.  Maximum Length: 500 characters. */
    public var tabLabel: String?

    public init(initialValue: String? = nil, tabLabel: String? = nil) {
        self.initialValue = initialValue
        self.tabLabel = tabLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case initialValue
        case tabLabel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(initialValue, forKey: .initialValue)
        try container.encodeIfPresent(tabLabel, forKey: .tabLabel)
    }

    public static func == (lhs: BulkSendingCopyTab, rhs: BulkSendingCopyTab) -> Bool {
        lhs.initialValue == rhs.initialValue &&
            lhs.tabLabel == rhs.tabLabel
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(initialValue?.hashValue)
        hasher.combine(tabLabel?.hashValue)
    }
}
