//
// DobInformationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/**  */
public final class DobInformationInput: Content, Hashable {
    /** Specifies the recipient's date, month, and year of birth. */
    public var dateOfBirth: String?
    /** Specifies the display level for the recipient. Valid values are: * `ReadOnly` * `Editable` * `DoNotDisplay` */
    public var displayLevelCode: String?
    /** A Boolean value that specifies whether the information must be returned in the response. */
    public var receiveInResponse: String?

    public init(dateOfBirth: String? = nil, displayLevelCode: String? = nil, receiveInResponse: String? = nil) {
        self.dateOfBirth = dateOfBirth
        self.displayLevelCode = displayLevelCode
        self.receiveInResponse = receiveInResponse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dateOfBirth
        case displayLevelCode
        case receiveInResponse
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dateOfBirth, forKey: .dateOfBirth)
        try container.encodeIfPresent(displayLevelCode, forKey: .displayLevelCode)
        try container.encodeIfPresent(receiveInResponse, forKey: .receiveInResponse)
    }

    public static func == (lhs: DobInformationInput, rhs: DobInformationInput) -> Bool {
        lhs.dateOfBirth == rhs.dateOfBirth &&
            lhs.displayLevelCode == rhs.displayLevelCode &&
            lhs.receiveInResponse == rhs.receiveInResponse
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dateOfBirth?.hashValue)
        hasher.combine(displayLevelCode?.hashValue)
        hasher.combine(receiveInResponse?.hashValue)
    }
}
