//
// DowngradRequestBillingInfoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/**  */
public final class DowngradRequestBillingInfoResponse: Content, Hashable {
    public var downgradePlanInformation: DowngradePlanUpdateResponse?
    /** The payment method used for the billing plan. Valid values are:  - `NotSupported` - `CreditCard` - `PurchaseOrder` - `Premium` - `Freemium` - `FreeTrial` - `AppStore` - `DigitalExternal` - `DirectDebit` */
    public var paymentMethod: String?

    public init(downgradePlanInformation: DowngradePlanUpdateResponse? = nil, paymentMethod: String? = nil) {
        self.downgradePlanInformation = downgradePlanInformation
        self.paymentMethod = paymentMethod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case downgradePlanInformation
        case paymentMethod
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(downgradePlanInformation, forKey: .downgradePlanInformation)
        try container.encodeIfPresent(paymentMethod, forKey: .paymentMethod)
    }

    public static func == (lhs: DowngradRequestBillingInfoResponse, rhs: DowngradRequestBillingInfoResponse) -> Bool {
        lhs.downgradePlanInformation == rhs.downgradePlanInformation &&
            lhs.paymentMethod == rhs.paymentMethod
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(downgradePlanInformation?.hashValue)
        hasher.combine(paymentMethod?.hashValue)
    }
}
