//
// IdCheckSecurityStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/**  */
public final class IdCheckSecurityStep: Content, Hashable {
    /** Type of authorization used for the security check. */
    public var authType: String?

    public init(authType: String? = nil) {
        self.authType = authType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case authType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(authType, forKey: .authType)
    }

    public static func == (lhs: IdCheckSecurityStep, rhs: IdCheckSecurityStep) -> Bool {
        lhs.authType == rhs.authType
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(authType?.hashValue)
    }
}
