//
// NameValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/** A name-value pair that describes an item and provides a value for the item. */
public final class NameValue: Content, Hashable {
    public var errorDetails: ErrorDetails?
    /** The name of the item. */
    public var name: String?
    /** The initial value of the item. */
    public var originalValue: String?
    /** The current value of the item. */
    public var value: String?

    public init(errorDetails: ErrorDetails? = nil, name: String? = nil, originalValue: String? = nil, value: String? = nil) {
        self.errorDetails = errorDetails
        self.name = name
        self.originalValue = originalValue
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errorDetails
        case name
        case originalValue
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errorDetails, forKey: .errorDetails)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(originalValue, forKey: .originalValue)
        try container.encodeIfPresent(value, forKey: .value)
    }

    public static func == (lhs: NameValue, rhs: NameValue) -> Bool {
        lhs.errorDetails == rhs.errorDetails &&
            lhs.name == rhs.name &&
            lhs.originalValue == rhs.originalValue &&
            lhs.value == rhs.value
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(errorDetails?.hashValue)
        hasher.combine(name?.hashValue)
        hasher.combine(originalValue?.hashValue)
        hasher.combine(value?.hashValue)
    }
}
