//
// RecipientRules.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/**  */
public final class RecipientRules: Content, Hashable {
    /**  */
    public var conditionalRecipients: [ConditionalRecipientRule]?

    public init(conditionalRecipients: [ConditionalRecipientRule]? = nil) {
        self.conditionalRecipients = conditionalRecipients
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case conditionalRecipients
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(conditionalRecipients, forKey: .conditionalRecipients)
    }

    public static func == (lhs: RecipientRules, rhs: RecipientRules) -> Bool {
        lhs.conditionalRecipients == rhs.conditionalRecipients
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(conditionalRecipients?.hashValue)
    }
}
