//
// ReportInProductList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/**  */
public final class ReportInProductList: Content, Hashable {
    /**  */
    public var reports: [ReportInProductListItem]?

    public init(reports: [ReportInProductListItem]? = nil) {
        self.reports = reports
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reports
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reports, forKey: .reports)
    }

    public static func == (lhs: ReportInProductList, rhs: ReportInProductList) -> Bool {
        lhs.reports == rhs.reports
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(reports?.hashValue)
    }
}
