//
// UserSignaturesInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import AnyCodable
import Foundation
import Vapor

/**  */
public final class UserSignaturesInformation: Content, Hashable {
    /** An array of  `userSignature` objects. */
    public var userSignatures: [UserSignature]?

    public init(userSignatures: [UserSignature]? = nil) {
        self.userSignatures = userSignatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userSignatures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userSignatures, forKey: .userSignatures)
    }

    public static func == (lhs: UserSignaturesInformation, rhs: UserSignaturesInformation) -> Bool {
        lhs.userSignatures == rhs.userSignatures
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(userSignatures?.hashValue)
    }
}
