//
// PaymentGatewayAccountsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

open class PaymentGatewayAccountsAPI {
    public enum PaymentGatewayAccountsGetAllPaymentGatewayAccounts {
        case http200(value: PaymentGatewayAccountsInfo?, raw: ClientResponse)
        case http400(value: ErrorDetails?, raw: ClientResponse)
        case http0(value: PaymentGatewayAccountsInfo?, raw: ClientResponse)
    }

    /**
     List payment gateway accounts

     GET /v2.1/accounts/{accountId}/payment_gateway_accounts

     This method returns a list of payment gateway accounts and basic information about them.

     - parameter accountId: (path) The external account number (int) or account ID GUID.
     - returns: `EventLoopFuture` of `PaymentGatewayAccountsGetAllPaymentGatewayAccounts`
     */
    open class func paymentGatewayAccountsGetAllPaymentGatewayAccounts(accountId: String, headers: HTTPHeaders = DocuSignAPI.customHeaders, beforeSend: (inout ClientRequest) throws -> Void = { _ in }) -> EventLoopFuture<PaymentGatewayAccountsGetAllPaymentGatewayAccounts> {
        var path = "/v2.1/accounts/{accountId}/payment_gateway_accounts"
        let accountIdPreEscape = String(describing: accountId)
        let accountIdPostEscape = accountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{accountId}", with: accountIdPostEscape, options: .literal, range: nil)
        let URLString = DocuSignAPI.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.GET, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)

            try beforeSend(&request)
        }.flatMapThrowing { response -> PaymentGatewayAccountsGetAllPaymentGatewayAccounts in
            switch response.status.code {
            case 200:
                return .http200(value: try? response.content.decode(PaymentGatewayAccountsInfo.self), raw: response)
            case 400:
                return .http400(value: try? response.content.decode(ErrorDetails.self), raw: response)
            default:
                return .http0(value: try? response.content.decode(PaymentGatewayAccountsInfo.self), raw: response)
            }
        }
    }
}
